name: Terraform

on:
  push:
    branches:
      - main

jobs:
  dev:
    name: "Developpement"
    runs-on: ubuntu-latest

    environment:
      name: dev

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      WORKING_DIRECTORY: ./dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{env.WORKING_DIRECTORY}}

  accept:
    name: "Acceptation"
    runs-on: ubuntu-latest
    needs: [dev]

    environment:
      name: accept

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      WORKING_DIRECTORY: ./accept

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{env.WORKING_DIRECTORY}}

  prod:
    name: "Production"
    runs-on: ubuntu-latest
    needs: [accept]

    environment:
      name: prod

    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
      WORKING_DIRECTORY: ./prod

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ${{env.WORKING_DIRECTORY}}/code

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{env.WORKING_DIRECTORY}}/code

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{env.WORKING_DIRECTORY}}/code
